### ISSUE TITLE
Re-add export menu functionality

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#2898]
We need to add functionality to the export menu:

- [x] ~~Dropbox~~
- [x] Gist
- [x] Gitlab snippet (see https://github.com/codimd/server/issues/508)
- [x] Markdown (see hedgedoc/react-client#627)
- [ ] HTML (see hedgedoc/hedgedoc#2889)

**Comment by ErikMichelson** [comment]
With only HTML export remaining, which has its own issue, this can be closed.
