### ISSUE TITLE
Rename to HedgeDoc

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#452]
This is a tracking issue for everything that needs to be done to release 1.6.1 under the new 'HedgeDoc' branding.

- [x] Get a logo
  - In the works over at https://community.codimd.org/t/time-to-find-the-hedgedoc-logo/171
- [x] Replace all references in code/UI
  - Already started by @ErikMichelson in https://github.com/codimd/server/tree/misc/renaming
  - Mostly done, some changes are blocked by things below
  - PR: #453 
- [x] Rename the [translation project](https://poeditor.com/join/project/1OpGjF2Jir)
  - I think @SISheogorath is admin there?
  - Don't forget moving `translate.codimd.org` to `translate.hedgedoc.org`
- [x] Rename the [mastodon account](https://social.snopyta.org/@CodiMD)
  - Don't forget moving `social.codimd.org`
- [x] Redirect `codimd.org` to `hedgedoc.org/what-happened-to-codimd` or similar (should this contain anything else besides what's already on the history page of the landing page?)
  - Basically a page explaining the rename
- [x] Rename discourse and redirect community.codimd.org (will happen after #453)
- [x] Rename `#codimd:matrix.org` to `#hedgedoc:matrix.org`
- [x] Add subdomains (or wildcard cname entry?) for hedgedoc.net
- [x] Move GitHub repos to github.com/hedgedoc
  - [x] github.com/hedgedoc/hedgedoc
  - [x] github.com/hedgedoc/cli
  - [x] github.com/hedgedoc/container
  - [x] github.com/hedgedoc/meta-marked
  - [x] github.com/hedgedoc/js-sequence-diagrams
- [x] Spin up demo.hedgedoc.org (will happen after #453)
- [x] Explain the renaming in docs/history.md (happens in #453)
- [x] Move the docker image to quay.io/repository/hedgedoc/hedgedoc
- [x] Rename the cloudron app: https://git.cloudron.io/cloudron/codimd-app
- [x] Ask the linuxserver guys to rename https://hub.docker.com/r/linuxserver/codimd
  - Or just also push our image to Docker Hub
- [x] Ask the YunoHost guys to rename https://github.com/YunoHost-Apps/codimd_ynh
- [x] Change names in github.com/codimd/cli (In-Progress https://github.com/codimd/cli/pull/40)
- [x] Take new Screenshot for README.md

**Comment by SISheogorath** [comment]
Main blockers are currently the logo and maybe a slogan.

As soon as we have a logo, I think it makes sense to rename user-facing services and social media.

**Comment by ErikMichelson** [comment]
I want to raise a question: Do we want to keep the name for the backend-repo as "server" after transferring to the new namespace? 

There are many opensource projects that follow the approach of using the name of the software for their primary repository too. If we did so too, it would be 'hedgedoc/hedgedoc'. The advantage of using the software name as repository name is that forks as well as the directory after cloning have a more meaningful name.

**Comment by danyork** [comment]
Hi. I just learned about CodiMD this week, as did, I suspect, a good number of other people, because the [IETF](https://www.ietf.org/) switched from Etherpad to CodiMD for recording meeting notes for their sessions this week.[1] As I started to tell other people about (and tweet about) CodiMD, I was surprised to now learn it is changing its name again. I've read through the various issues and understand why.  To help prepare people who might just be learning about CodiMD for the name change, may I suggest that you add a line to the top of the **current** README.md that says something like:

**NOTE: CodiMD is in the process of [changing its name to HedgeDoc](https://github.com/codimd/server/issues/452).**

![codimd-readme](https://user-images.githubusercontent.com/41662/88836106-36a75880-d1a4-11ea-92c0-ed6ba1f1471d.jpg)

That way you are getting people ready for all the changes you are outlining here.

Best wishes with the renaming - and thanks for developing such an incredibly useful tool!

_[1] You can see this in action if you go to [the IETF 108 meeting agenda](https://datatracker.ietf.org/meeting/agenda/) and look on the right side where there is an icon of a square box and a pencil. The tooltip still says "Etherpad for notetakers", but when you click the link, you go to a CodiMD link,_

**Comment by FaZeBase** [comment]
Name change reported to the Cloudron team.
https://git.cloudron.io/cloudron/codimd-app/-/issues/4

**Comment by slel** [comment]
Can someone create demo.hedgedoc.org and make it redirect to demo.codimd.org for now?

**Comment by DerMolly** [comment]
https://demo.hedgedoc.org should already work

**Comment by utybo** [comment]
Seems like hedgedoc.org is down or is that just me?

**Comment by DerMolly** [comment]
hedgedoc.org is currently not online. It will be once [hedgedoc.github.io](https://github.com/hedgedoc/hedgedoc.github.io) is finished and will link to that page.

**Comment by SISheogorath** [comment]
@CHBMB could you look into this for the linuxserver.io part?

**Comment by gramakri** [comment]
I maintain the Cloudron package and I have started the renaming, will leave a note here when done.

**Comment by gramakri** [comment]
I have renamed our repo and fixed the app package. Once 1.7 is out, we can push it all out - https://git.cloudron.io/cloudron/hedgedoc-app/-/commit/d9dc9d155f111993edab4b106e66d80faa9ac0db . Is there a logo somewhere _without_ the HedgeDoc text in it?

**Comment by SISheogorath** [comment]
@gramakri there are logo variants without a name available in the logo repository: https://github.com/hedgedoc/hedgedoc-logo

**Comment by gramakri** [comment]
@SISheogorath thanks, updated the logo as well! We are good to go from cloudron side. Of course, I need to test out the 1.7 release upgrade itself once it's available.

**Comment by InnayTool** [comment]
I think all renaming tasks are done!

**Comment by SimJoSt** [comment]
In the following repo the description (not the readme) is still mentioning CodiMD: https://github.com/hedgedoc/cli  
Might be worth correcting 😄
