### ISSUE TITLE
PrivateAPI: Methods needed by the frontend

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#987]
I wrote down here all the different routes we would need in the private API to connect to the frontend.
- [ ] explore page (see #3833)
    - [ ] GET `/explore/all` - list of accessible notes, maybe paginated
    - [ ] GET `/explore/created` - list of notes the user has created
- [ ] auth (related to https://github.com/hedgedoc/hedgedoc/issues/1006)
	- [x] POST `/auth/local/*` implementation moved to #1515
	- [x] POST `/auth/ldap/:provider`
	- [ ] GET `/auth/saml/:provider`
	- [ ] GET `/auth/oauth2/:provider`
	- [ ] GET `/auth/gitlab/:provider`
	- [ ] GET `/auth/github`
	- [ ] GET `/auth/facebook`
	- [ ] GET `/auth/twitter`
	- [ ] GET `/auth/dropbox`
	- [ ] GET `/auth/google`
- [x] config (see #980)
	- [x] GET `/config`
- [x] me (see #992)
	- [x] GET `/me` 
	- [x] GET `/me/media`
	- [x] DELETE `/me`
	- [x] POST `/me/profile`
	- [x] history (see #981)
		- [x] POST `/history` (override current history with new history)
		- [x] DELETE `/history`
		- [x] PUT `/history/:noteId` (change pin status)
		- [x] DELETE `/history/:noteId`
- [x] media (see #1057)
	- [x] POST `/media/proxy`
	- [x] POST `/media/upload`
- [x] notes (see #1058)
	- [x] GET `/notes/:noteId`
	- [x] GET `/notes/:noteId/media`
	- [x] POST `/notes/`
	- [x] POST `/notes/:noteId`
	- [x] DELETE `/notes/:noteId`
	- [x] GET `/notes/:noteId/revisions/:timestamp`
	- [x] GET `/notes/:noteId/revisions`
- [x] notes (?) 
	- [x] GET `/notes/:noteId/content`
	- [x] GET `/notes/:noteId/metadata`
	- [x] PUT `/notes/:noteIdOrAlias/metadata/permissions`
	- [x] PUT `/notes/:noteId`
- [x] alias (see #1359) 
	- [x] POST `/alias`
	- [x] PUT `/alias/:alias`
	- [x] DELETE `/alias/:alias`
- [x] tokens
- [x] users
	- [x] GET `/users/:userid`

**Comment by fvalle1** [comment]
Is '/auth/google' still not available?

**Comment by mrdrogdrog** [comment]
We haven't implemented any of the oauth login strategies yet.

**Comment by mrdrogdrog** [comment]
The docs are for HedgeDoc 1. This issue is about HedgeDoc 2. Google auth should work in HedgeDoc 1.

**Comment by DerMolly** [comment]
This issue is no longer needed as there is https://github.com/hedgedoc/hedgedoc/issues/1006 for the auth backends and https://github.com/hedgedoc/hedgedoc/issues/3833 for the explore page.
